# Generated by Django 4.1 on 2024-05-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='top_name',
            field=models.CharField(max_length=264, unique=True),
        ),
    ]
